# Generated by Django 3.0.7 on 2024-11-18 06:04

from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='tasks',
        ),
    ]
